V0.13.0
tangrams/tangram-docs pull request #222
Opened 2017-06-27 17:43 UTC by meetar

2017-07-06 15:59 UTC, bcamper commented on pages/Javascript-API.md
> +#### `queryFeatures()`
There are several other options we need to incorporate here, such as `visible`, `unique`, `group_by`, `geometry`. These should be well documented (along with some examples that I think are worth incorporating) in https://github.com/tangrams/tangram/pull/566.

2017-07-06 16:00 UTC, bcamper requested changes
Made some small changes, but want to make sure we incorporate full docs for `queryFeatures()` method too.

2017-08-25 15:50 UTC, bcamper commented
@meetar -- we still need to incorporate the `queryFeatures()` details.

2017-08-29 15:36 UTC, bcamper commented
Good to merge?

2017-08-29 15:41 UTC, meetar commented
:+1:

2017-08-29 15:43 UTC, merged